name: static analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-22.04

    name: Source Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --dev --no-interaction --no-progress

      - name: Execute type checking
        run: composer analyse
